package livesmoke

import (
	"errors"
	"fmt"
	"path"
	"path/filepath"
	"regexp"
	"strings"
	"time"
	"unicode"
)

type IssueRef struct {
	Identifier string `json:"identifier"`
	URL        string `json:"url"`
	Title      string `json:"title,omitempty"`
	Path       string `json:"path,omitempty"`
}

type Report struct {
	StartedAt          time.Time       `json:"started_at"`
	ConfigPath         string          `json:"config_path"`
	SmokeConfig        string          `json:"smoke_config"`
	WorkspaceRoot      string          `json:"workspace_root"`
	FakeAgent          bool            `json:"fake_agent"`
	ApplyMerge         bool            `json:"apply_merge"`
	Issues             []IssueRef      `json:"issues"`
	Commands           []string        `json:"commands"`
	CommandResults     []CommandResult `json:"command_results,omitempty"`
	ReportPath         string          `json:"report_path,omitempty"`
	PublicReportPath   string          `json:"public_report_path,omitempty"`
	FinalStatusRan     bool            `json:"final_status_ran"`
	ManualIntervention string          `json:"manual_intervention,omitempty"`
}

type CommandResult struct {
	Command  string `json:"command"`
	Success  bool   `json:"success"`
	ExitCode int    `json:"exit_code"`
	Error    string `json:"error,omitempty"`
}

func ValidateEnvironment(env map[string]string, applyMerge bool) error {
	if env["LIVE_LINEAR"] != "1" {
		return errors.New("LIVE_LINEAR=1 is required before the live smoke harness may read or mutate Linear")
	}
	if strings.TrimSpace(env["LINEAR_API_KEY"]) == "" {
		return errors.New("LINEAR_API_KEY is required")
	}
	if applyMerge && env["LIVE_SMOKE_APPLY"] != "1" {
		return errors.New("LIVE_SMOKE_APPLY=1 is required with --apply-merge")
	}
	return nil
}

func DisposableIssueDescription(path string) string {
	return fmt.Sprintf(`## Goal
Add a tiny disposable marker for an opt-in Agent Machine live smoke run.

## Scope
Allowed paths:
- %s

Out of scope:
- Runner behavior changes.
- Project configuration changes.
- Production code changes.
- Changes outside the allowed path.

## Requirements
- Create %s if it does not exist.
- The file must state that it was created by the opt-in live smoke harness.
- Do not modify any other file.

## Acceptance Criteria
- Exactly one tracked file is changed: %s.
- Validation passes.
- The issue can move through the normal Agent Machine handoff flow to Human Review.

## Validation
- mise exec go -- go test ./...
- git diff --check`, path, path, path)
}

func SmokeMarkerContent(identifier, path string) string {
	name := strings.TrimSuffix(filepath.Base(path), filepath.Ext(path))
	title := strings.ReplaceAll(name, "-", " ")
	if strings.TrimSpace(identifier) == "" {
		identifier = "unknown"
	}
	return fmt.Sprintf("# %s\n\nCreated by the opt-in Agent Machine live smoke harness for %s.\n", titleCase(title), identifier)
}

func MarkdownReport(report Report) string {
	var b strings.Builder
	title := "Agent Machine Live Smoke Evidence"
	if !report.StartedAt.IsZero() {
		title += " " + report.StartedAt.UTC().Format("20060102T150405Z")
	}
	fmt.Fprintf(&b, "# %s\n\n", title)
	fmt.Fprintf(&b, "Generated by the opt-in Agent Machine live smoke harness.\n\n")
	fmt.Fprintf(&b, "## Scope\n\n")
	fmt.Fprintf(&b, "- Source config: `%s`\n", report.ConfigPath)
	fmt.Fprintf(&b, "- Smoke config: `%s`\n", report.SmokeConfig)
	fmt.Fprintf(&b, "- Workspace root: `%s`\n", report.WorkspaceRoot)
	fmt.Fprintf(&b, "- Fake Agent: `%t`\n", report.FakeAgent)
	fmt.Fprintf(&b, "- Merge apply requested: `%t`\n", report.ApplyMerge)
	if report.ManualIntervention != "" {
		fmt.Fprintf(&b, "- Manual intervention: %s\n", report.ManualIntervention)
	} else {
		fmt.Fprintf(&b, "- Manual intervention: none recorded by the harness between listed commands\n")
	}
	fmt.Fprintf(&b, "\n## Issues\n\n")
	if len(report.Issues) == 0 {
		fmt.Fprintf(&b, "- No issues recorded.\n")
	} else {
		for _, issue := range report.Issues {
			label := issue.Identifier
			if label == "" {
				label = issue.Title
			}
			if issue.URL != "" {
				fmt.Fprintf(&b, "- [%s](%s)", label, issue.URL)
			} else {
				fmt.Fprintf(&b, "- %s", label)
			}
			if issue.Title != "" && issue.Title != label {
				fmt.Fprintf(&b, ": %s", issue.Title)
			}
			if issue.Path != "" {
				fmt.Fprintf(&b, " (`%s`)", issue.Path)
			}
			fmt.Fprintln(&b)
		}
	}
	fmt.Fprintf(&b, "\n## Commands\n\n")
	results := report.CommandResults
	if len(results) == 0 {
		if len(report.Commands) == 0 {
			fmt.Fprintf(&b, "- No commands recorded.\n")
		} else {
			for _, command := range report.Commands {
				fmt.Fprintf(&b, "- `%s` -> recorded (legacy report; exit status unavailable)\n", command)
			}
		}
	} else {
		for _, result := range results {
			status := "failed"
			if result.Success {
				status = "passed"
			}
			fmt.Fprintf(&b, "- `%s` -> %s", result.Command, status)
			if result.ExitCode != 0 {
				fmt.Fprintf(&b, " (exit %d)", result.ExitCode)
			}
			if result.Error != "" {
				fmt.Fprintf(&b, ": %s", result.Error)
			}
			fmt.Fprintln(&b)
		}
	}
	fmt.Fprintf(&b, "\n## Evidence Boundary\n\n")
	if len(report.CommandResults) == 0 && len(report.Commands) > 0 {
		fmt.Fprintf(&b, "This legacy report records harness-controlled commands but not their exit status. It does not replace PR review, CI checks, Linear state inspection, or code-host merge evidence.\n")
	} else {
		fmt.Fprintf(&b, "This report records the harness-controlled commands and their exit status. It does not replace PR review, CI checks, Linear state inspection, or code-host merge evidence.\n")
	}
	if report.ReportPath != "" {
		fmt.Fprintf(&b, "\nMachine report: `%s`\n", report.ReportPath)
	}
	return b.String()
}

func PublicReportPath(reportPath string) string {
	base := strings.TrimSuffix(path.Base(reportPath), path.Ext(reportPath))
	if base == "" || base == "." {
		base = "live-smoke"
	}
	return filepath.Join("docs", "smoke", base+"-evidence.md")
}

func PromptPath(args []string) (string, error) {
	for _, arg := range args {
		if strings.HasPrefix(arg, "@") && len(arg) > 1 {
			return strings.TrimPrefix(arg, "@"), nil
		}
	}
	return "", errors.New("missing @prompt path argument")
}

func IssueIdentifierFromPrompt(prompt string) string {
	re := regexp.MustCompile(`(?m)(?:Identifier:\s*|Issue:\s*)(CAG-[0-9]+)\b`)
	match := re.FindStringSubmatch(prompt)
	if len(match) == 2 {
		return match[1]
	}
	return ""
}

func AllowedPathFromPrompt(prompt string) (string, error) {
	lines := strings.Split(prompt, "\n")
	inAllowed := false
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.EqualFold(trimmed, "Allowed paths:") {
			inAllowed = true
			continue
		}
		if !inAllowed {
			continue
		}
		if strings.HasSuffix(trimmed, ":") && !strings.EqualFold(trimmed, "Allowed paths:") {
			break
		}
		if strings.HasPrefix(trimmed, "- ") || strings.HasPrefix(trimmed, "* ") {
			path := strings.TrimSpace(strings.TrimPrefix(strings.TrimPrefix(trimmed, "- "), "* "))
			path = strings.Trim(path, "`")
			if path == "" {
				continue
			}
			if !strings.HasPrefix(path, "docs/smoke/") || strings.Contains(path, "..") || filepath.IsAbs(path) {
				return "", fmt.Errorf("fake smoke agent refuses non-docs/smoke allowed path %q", path)
			}
			return path, nil
		}
	}
	return "", errors.New("no docs/smoke allowed path found in prompt")
}

func titleCase(value string) string {
	words := strings.Fields(value)
	for i, word := range words {
		runes := []rune(word)
		if len(runes) == 0 {
			continue
		}
		runes[0] = unicode.ToUpper(runes[0])
		words[i] = string(runes)
	}
	return strings.Join(words, " ")
}
